export const NOTE_LIST_REQUEST= "NOTE_REGISTER_REQUEST";
export const NOTE_LIST_SUCESS="NOTE_REGISTER_SUCESS";
export const NOTE_LIST_FAIL="NOTE_REGISTER_FAIL";

export const NOTE_CREATE_REQUEST= "NOTE_REGISTER_REQUEST";
export const NOTE_CREATE_SUCESS="NOTE_REGISTER_SUCESS";
export const NOTE_CREATE_FAIL="NOTE_REGISTER_FAIL";